FROM bcit.io/centos:<%= image.vars['centos_version'] %>

<%= snippet('labels', binding) -%>

# enable php7 & oracle repos then install system libs/utils, php-fpm, oracle-instantclient
RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
    http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
  && yum-config-manager --enable remi-php<%= image.vars['remi_php_repo'] -%> \
  && cd /etc/yum.repos.d \
  && wget http://yum.oracle.com/public-yum-ol7.repo \
  && wget http://yum.oracle.com/RPM-GPG-KEY-oracle-ol7 \
  && rpm --import RPM-GPG-KEY-oracle-ol7 \
  && yum-config-manager --enable ol7_oracle_instantclient \
  && yum update -y \
  && yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
  bzip2 \
  libxml2-devel \
  unzip \
  vim \
  zip \
  # php
  php-<%= image.vars['php_pkg_version'] -%>
<% image.vars['php_extensions'].each do |ext| -%> \
  php-<%= ext %>-<%= image.vars['php_pkg_version'] -%>
<% end -%>
<% image.vars['php_pecl'].each do |ext| -%> \
  php-pecl-<%= ext -%>
<% end -%> \
  # oracle-instantclient
  oracle-instantclient<%= image.vars['oracle-instantclient_version'] -%>-basic \
  oracle-instantclient<%= image.vars['oracle-instantclient_version'] -%>-devel \
  oracle-instantclient<%= image.vars['oracle-instantclient_version'] -%>-sqlplus \
  && yum clean all -y

# Link oracle-instantclient, set timezone, install composer, configure php-fpm 
# ENV TZ=America/Vancouver - set in docker-compose.yml
RUN echo /usr/lib/oracle/<%= image.vars['oracle-instantclient_version'] -%>/client64/lib > /etc/ld.so.conf.d/oracle-instantclient.conf \
  && ldconfig \
  && ln -snf /usr/share/zoneinfo/<%= image.vars['timezone'] -%> /etc/localtime \
  && echo <%= image.vars['timezone'] -%> > /etc/timezone \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && mkdir -p /run/php-fpm/ \
  && sed -i "s$/var/log/php-fpm/error.log$/dev/stderr$" /etc/php-fpm.conf \
  && sed -i s/127.0.0.1:9000/0.0.0.0:9000/ /etc/php-fpm.d/www.conf \
  && sed -i s/127.0.0.1/any/ /etc/php-fpm.d/www.conf \
  && chmod -R 775 /run/php-fpm \
  && chmod -R 775 /etc/php-fpm.d \
  && chmod -R 775 /etc/php.d

<% if image.variant == 'debug' -%>
# Configure default php.ini file based on environment; Install xdebug from PECL if we're building a DEV environment
# Production php.ini by default
RUN echo '=============== DEV flagged, Installing xdebug & dev config ===============' \ 
  && wget https://raw.githubusercontent.com/php/php-src/PHP-$(rpm -q --queryformat="%{VERSION}" php)/php.ini-development -O /etc/php.ini \
  && yum install -y php-pecl-xdebug \
  && php -v \
  && echo '=============== xdebug installed ===============' \
  && php -i
<% end -%>

WORKDIR /application

CMD ["php-fpm", "-F", "-O"]
