FROM bcit.io/centos:<%= image.vars['centos_tag'] %>

<%= snippet('labels', binding) -%>

# enable php7 & oracle repos then install system libs/utils, php-fpm
RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 --setopt=skip_missing_names_on_install=False install -e1 -d0 \
    http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
  && yum-config-manager --enable remi-php<%= image.vars['remi_php_repo'] -%> \
  && yum-config-manager -q --enable remi-php<%= image.vars['remi_php_repo'] -%> >/dev/null \
  && yum -y --setopt tsflags=nodocs --setopt timeout=5 --setopt=skip_missing_names_on_install=False install -e1 -d0 \
  bzip2 \
  libxml2-devel \
  unzip \
  vim \
  zip \
  php-<%= image.vars['php_pkg_version'] -%> \
<% image.vars['php_extensions'].each do |ext| -%>
  php-<%= ext %>-<%= image.vars['php_pkg_version'] -%> \
<% end -%>
<% image.vars['php_pecl'].each do |ext| -%> \
  php-pecl-<%= ext -%>
<% end -%> \
  && yum clean all -y

# Set timezone, install composer, configure php-fpm 
# ENV TZ=America/Vancouver - set in docker-compose.yml
RUN ln -snf /usr/share/zoneinfo/<%= image.vars['timezone'] -%> /etc/localtime \
  && echo <%= image.vars['timezone'] -%> > /etc/timezone \
  && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
  && mkdir -p /run/php-fpm/ \
  && sed -i "s$/var/log/php-fpm/error.log$/dev/stderr$" /etc/php-fpm.conf \
  && sed -i s/127.0.0.1:9000/0.0.0.0:9000/ /etc/php-fpm.d/www.conf \
  && sed -i s/127.0.0.1/any/ /etc/php-fpm.d/www.conf \
  && chmod -R 775 /run/php-fpm \
  && chmod -R 775 /etc/php-fpm.d \
  && chmod -R 775 /etc/php.d

ADD https://raw.githubusercontent.com/php/php-src/PHP-<%= image.vars['php_pkg_version'] %>/php.ini-development /etc/php.ini-development

WORKDIR /application

CMD ["php-fpm", "-F", "-O"]
