FROM bcit.io/centos:<%= image.vars['centos_tag'] %> as BUILDER

RUN yum -y  install \
    http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
 && rpmkeys --import /etc/pki/rpm-gpg/RPM-GPG-KEY-remi* /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-<%= image.vars['centos_version'] %> \
 && yum-config-manager -q --enable remi-php<%= image.vars['remi_php_repo'] -%> >/dev/null \
 && yum -y  install \
<% image.vars['os_packages'].each do |package| -%>
    <%= package %> \
<% end -%>
<% image.vars['builder_packages'].each do |package| -%>
    <%= package %> \
<% end -%>
    php-devel-<%= image.vars['php_version'] %>

RUN pecl channel-update pecl.php.net
<% image.vars['php_pecl_builds'].each do |pecl_package| -%>
RUN touch /etc/php.d/<%= pecl_package['order'] %>-timezonedb.ini
RUN pear config-set php_ini /etc/php.d/<%= pecl_package['order'] %>-timezonedb.ini
RUN pecl install <%= pecl_package['name'] %>

<% end -%>